name: firebase_app
description: "Get to know Firebase with Flutter"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  go_router: ^14.0.1
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  provider: ^6.1.2
  firebase_ui_auth: ^1.14.0
  firebase_messaging: ^14.9.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.1
  http: ^1.2.1
  easy_localization: ^3.0.7
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.4+4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.8.0
  intl_utils: ^2.6.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png
    - assets/user.jpeg
    - assets/play.png
    - assets/app.png
    - assets/click.png
    - assets/ticket.png
    - assets/logo.png
    - assets/avatar.png
    - assets/products.json
