// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxsrhZEx-mBCSU-5tOxQth4TbL2ejeDxM',
    appId: '1:447297017577:web:2d7f2e0de88af2a2860278',
    messagingSenderId: '447297017577',
    projectId: 'fir-572aa',
    authDomain: 'fir-572aa.firebaseapp.com',
    storageBucket: 'fir-572aa.appspot.com',
    measurementId: 'G-ZL8DV89T9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC369B2WDEEBrqIWPiLIsU-kiGHTIn4oUg',
    appId: '1:447297017577:android:fdd7e9eb96624c40860278',
    messagingSenderId: '447297017577',
    projectId: 'fir-572aa',
    storageBucket: 'fir-572aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAi7MN7vT12VG1ikmclLpbYeW0XxxCti4',
    appId: '1:447297017577:ios:cfb682f34046675e860278',
    messagingSenderId: '447297017577',
    projectId: 'fir-572aa',
    storageBucket: 'fir-572aa.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAi7MN7vT12VG1ikmclLpbYeW0XxxCti4',
    appId: '1:447297017577:ios:cfb682f34046675e860278',
    messagingSenderId: '447297017577',
    projectId: 'fir-572aa',
    storageBucket: 'fir-572aa.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxsrhZEx-mBCSU-5tOxQth4TbL2ejeDxM',
    appId: '1:447297017577:web:365b592c21aad97e860278',
    messagingSenderId: '447297017577',
    projectId: 'fir-572aa',
    authDomain: 'fir-572aa.firebaseapp.com',
    storageBucket: 'fir-572aa.appspot.com',
    measurementId: 'G-FCPX2LYZVQ',
  );
}
